package modelo.entidad;
// Generated 10-28-2022 08:25:48 PM by Hibernate Tools 4.3.1


import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String usuario;
     private String clave;
     private String nombre;
     private String apellido;
     private String telefono;
     private String email;
     private Date fechaCreacion;
     private Boolean activo;
     private Integer tipoUsuario;
     private Set<Remesa> remesas = new HashSet<Remesa>(0);
    
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    Calendar fecha = Calendar.getInstance();
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
    
    public Usuario() {
    }

    public Usuario(String usuario, String clave, String nombre, String apellido, String telefono, String email, Date fechaCreacion, Boolean activo, Integer tipoUsuario, Set<Remesa> remesas) {
       this.usuario = usuario;
       this.clave = clave;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.email = email;
       this.fechaCreacion = fechaCreacion;
       this.activo = activo;
       this.tipoUsuario = tipoUsuario;
       this.remesas = remesas;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        if(fechaCreacion != null){
            this.fechaCreacion = fechaCreacion;
        }else{
            try {
                this.fechaCreacion = formato.parse(dia+"/"+mes+"/"+año);
            } catch (ParseException ex) {
                Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public Integer getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(Integer tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public Set<Remesa> getRemesas() {
        return this.remesas;
    }
    
    public void setRemesas(Set<Remesa> remesas) {
        this.remesas = remesas;
    }




}


